### ISSUE TITLE
Lack of "use strict" with "let, const, function, class"

### ISSUE THREAD

**Issue by garrensweet** [appstract/laravel-elixir-env#2]
Laravel's `gulpfile.js` ships with `var elixir = require('laravel-elixir');`, I've tested with both, but for the purpose of this issue, let the following be an example of my code from my `gulpfile.js`

    const elixir = require('laravel-elixir');
    require('laravel-elixir-env');

    mix.webpack('app.js', 'public/assets/js/app.js');

Given that inside of my `resources/assets/js/app.js` file I have the following;

    console.log(process.env(APP_URL))

With the following defined in my `.env` file:

    APP_URL=http://<my_project>.dev

However, when running `gulp` from the command line, this is what I get:

    /home/vagrant/www/<my_project>/node_modules/laravel-elixir-env/index.js:6
    let envEntries = require('dotenv').config({ silent: true, path: envFile });
    ^^^
    SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

To solve this problem, simply `"use strict";` at the top of `laravel-elixir-env/index.js`.

**Comment by ovanschie** [comment]
Thank you for your contribution.

What node version are you using? I didn't came across this issue.

Will merge it anyway if it solves your issue.

Thanks again!

**Comment by garrensweet** [comment]
My node version is as follows:

     node -v
     > v5.10.1
