### ISSUE TITLE
SytnaxError: Unexpected Token when Gulping

### ISSUE THREAD

**Issue by nickbasile** [appstract/laravel-elixir-env#5]
Hi there,

I installed the package according to the documentation, and when I ran `Gulp` I received the following error output in my terminal.

```
{path to modules}/node_modules/laravel-elixir-env/index.js:14
    config: function (options = {}) {
                              ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> ({path to gulp file}/gulpfile.js:5:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

I was able to get it working by removing the default value from the function, but I doubt that is a proper fix for the issue.

**Comment by ovanschie** [comment]
I think you are on a bit old version of Node.js. Upgrading to a newer version will probably fix it for you, [Node 6.9 LTS](https://nodejs.org/en/) for example :)

**Comment by nickbasile** [comment]
Thanks @ovanschie! That did the trick :)

**Comment by dbr0** [comment]
I used this on my Laravel 5.3 app and after that I had some problems with node/npm. Keep in mind I'm a bit newb here so here are the Instructions I followed:

```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```
After that stuff might break:

```
mv node_modules node_modules_bak
sudo npm install
sudo npm rebuild node-sass
```

At this stage I still can't access my `.env` variables inside my webpacked scripts but I suppose that's another issue.

**Comment by ovanschie** [comment]
Hello @dbr0,

I don't really understand your issue. Is it related to this package? Then feel free to open a new issue here.

**Comment by dbr0** [comment]
I got the same error as nick but after upgrading to latest version I had some issues with other packages and since I was already here I added how I resolved them so others won't have to google for a solution for 20mins as I did :)

I opened another issue for my problem.
