### ISSUE TITLE
Getting undefined for process.env.MY_ENV_VARIABLE

### ISSUE THREAD

**Issue by dbr0** [appstract/laravel-elixir-env#7]
Hi, I'm trying to use this lib to get my Pusher key `PUSHER_KEY` from my `.env` file

Here is (part of) my `gulpfile.js`

```
var elixir = require('laravel-elixir');
require('laravel-elixir-env');
...
elixir(function(mix) {
    mix.webpack('echo.js','./resources/assets/js/');
});
...
```

My echo.js

```
import Echo from "laravel-echo"
console.log('PK:'+process.env.PUSHER_KEY);
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.PUSHER_KEY,
    cluster: 'eu',
    encrypted: true
});
```

gulp passes but I get console log: `PK:undefined`

If I `console.log(process)` I get some huge object with which I don't know what to do with or is there anywhere in it my PUSHER_KEY.

Thanks!

**Comment by ovanschie** [comment]
Does console.log(process.env) contain any of your variables?
What is the location of your .env?

**Comment by dbr0** [comment]
This is the output of `console.log(process.env)`:


![screenshot from 2017-01-25 15-05-13](https://cloud.githubusercontent.com/assets/13360206/22293430/c56d989a-e30f-11e6-9c00-e7cdd9af2e21.png)

`.env` is in my project root.

**Comment by ovanschie** [comment]
I pushed an update to the package. Can you try version 0.1.2 and see if it works for you now?

**Comment by dbr0** [comment]
Still the same.

**Comment by dbr0** [comment]
My bad. I was logging `process` instead of `process.env.MY_VARIABLE`. It's all working now.

Thanks for the quick reply!
