### ISSUE TITLE
LaraveMix version

### ISSUE THREAD

**Issue by ctf0** [appstract/laravel-elixir-env#8]
is there a chance to have a version for LaraveMix ?

**Comment by teuunn** [comment]
@ctf0 it's on our to-do list! Although PR's are welcome.

**Comment by ctf0** [comment]
i wish i could help, but webpack is kinda like a rocket science to me 😱 , 
however i believe it would be better if there was another branch for the mix version, so ppl with old version of laravel still can use it.

**Comment by ovanschie** [comment]
It will probably be a separate package.

**Comment by zanematthew** [comment]
Is this not already handled via LaravelMix?

https://github.com/JeffreyWay/laravel-mix/pull/464/files

**Comment by ovanschie** [comment]
https://github.com/JeffreyWay/laravel-mix/pull/464 is merged so it should work in mix.
